FIELD_MAPPING = {
    "_project": "project_name",  # Use Bubble's `_id` as the project name if needed
    "file_format": "file_format",
    "incl_actual_recon": "incl_actual_recon",
    "first_row": "first_row",
    "last_row": "last_row",
    "recon_accuracy": "recon_accuracy",
    "northwall_DD": "northwall_approximate_DD",
    "Hangingwall_DD": "Hangingwall_approximate_DD",
    "crown_Dip": "crown_Dip",
    "Floor_Dip": "Floor_Dip",
    "include_model_recon": "include_model_recon",
    "first_step": "first_step",
    "last_step": "last_step",
    "search_distance": "search_distance",
    "include_geom": "include_geom",
    # Mappings to fix duplicate reference key warnings
    "Model_Construction": "model_construction",
    "Model_Construction_Detail": "model_construction_detail",
    "ground_surface_elevation": "ground_surface_elevation",
    "_include_topo": "topo_enabled",
    "_include_area_of_interest": "aoi_enabled",
    "_include_development": "dev_enabled",
    "_include_historical_mining": "hist_enabled",
    "_faults_geometry_filename": "fault_global_file",
    "Insitu_stress_options": "stress_option",
}
